name: cpf
description: Biblioteca para manipulação de CPF.
version: 1.0.0
homepage: https://github.com/dartbrasil/cep
author: Rodrigo Muniz <rodrigo.temiski1995@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
